name: 100k-hours-lingvo
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=0_gnu
  - alsa-lib=1.1.5=h516909a_1002
  - aria2=1.34.0=0
  - bazel=2.1.0=he1b5a44_0
  - binutils_impl_linux-64=2.34=h53a641e_5
  - c-ares=1.11.0=h470a237_1
  - ca-certificates=2020.4.5.1=hecc5488_0
  - certifi=2020.4.5.1=py37hc8dfbb8_0
  - fontconfig=2.13.1=h1056068_1002
  - freetype=2.10.2=he06d7ca_0
  - giflib=5.2.1=h516909a_2
  - icu=67.1=he1b5a44_0
  - jpeg=9c=h14c3975_1001
  - lcms2=2.9=hbd6801e_1
  - ld_impl_linux-64=2.34=h53a641e_5
  - libffi=3.2.1=he1b5a44_1007
  - libgomp=9.2.0=h24d8f2e_2
  - libiconv=1.15=h516909a_1006
  - libpng=1.6.37=hed695b0_1
  - libssh2=1.9.0=hab1572f_2
  - libstdcxx-ng=9.2.0=hdf63c60_2
  - libtiff=4.1.0=hc7e4089_6
  - libuuid=2.32.1=h14c3975_1000
  - libwebp-base=1.1.0=h516909a_3
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.10=h72b56ed_1
  - lz4-c=1.9.2=he1b5a44_1
  - ncurses=6.1=hf484d3e_1002
  - openjdk=11.0.1=h600c080_1018
  - openssl=1.1.1g=h516909a_0
  - pip=20.1.1=pyh9f0ad1d_0
  - pthread-stubs=0.4=h14c3975_1001
  - python=3.7.6=h8356626_5_cpython
  - python_abi=3.7=1_cp37m
  - readline=8.0=hf8c457e_0
  - setuptools=46.4.0=py37hc8dfbb8_0
  - sqlite=3.30.1=hcee41ef_0
  - tk=8.6.10=hed695b0_0
  - wheel=0.34.2=py_1
  - xorg-fixesproto=5.0=h14c3975_1002
  - xorg-inputproto=2.3.2=h14c3975_1002
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxfixes=5.0.3=h516909a_1004
  - xorg-libxi=1.7.10=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-libxtst=1.2.3=h516909a_1002
  - xorg-recordproto=1.14.2=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h516909a_0
  - zlib=1.2.11=h516909a_1006
  - zstd=1.4.4=h6597ccf_3
  - pip:
    - absl-py==0.9.0
    - argon2-cffi==20.1.0
    - astroid==2.4.2
    - astunparse==1.6.3
    - attrs==19.3.0
    - awscli==1.18.87
    - backcall==0.2.0
    - backports-csv==1.0.7
    - beautifulsoup4==4.9.1
    - bleach==3.1.5
    - botocore==1.17.10
    - cachetools==4.1.1
    - cffi==1.14.2
    - chardet==3.0.4
    - cloud-tpu-client==0.10
    - cloud-tpu-profiler==1.15.0
    - colorama==0.4.3
    - contextlib2==0.6.0.post1
    - cycler==0.10.0
    - decorator==4.4.2
    - defusedxml==0.6.0
    - dill==0.3.2
    - docopt==0.6.2
    - docutils==0.15.2
    - entrypoints==0.3
    - future==0.18.2
    - gast==0.3.3
    - google-api-core==1.22.2
    - google-api-python-client==1.8.0
    - google-auth==1.18.0
    - google-auth-httplib2==0.0.4
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.2.0
    - googleapis-common-protos==1.52.0
    - grpcio==1.30.0
    - gviz-api==1.9.0
    - h5py==2.10.0
    - httplib2==0.18.1
    - idna==2.10
    - importlib-metadata==1.7.0
    - ipdb==0.13.2
    - ipykernel==5.3.4
    - ipython==7.16.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - isort==4.3.21
    - jedi==0.17.1
    - jinja2==2.11.2
    - jmespath==0.10.0
    - jsonpatch==1.26
    - jsonpointer==2.0
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.6
    - jupyter-console==6.1.0
    - jupyter-core==4.6.3
    - keras-preprocessing==1.1.2
    - kiwisolver==1.2.0
    - lazy-object-proxy==1.4.3
    - markdown==3.2.2
    - markupsafe==1.1.1
    - matplotlib==3.2.2
    - mccabe==0.6.1
    - mistune==0.8.4
    - model-pruning-google-research==0.0.3
    - mpmath==1.1.0
    - nbconvert==5.6.1
    - nbformat==5.0.7
    - notebook==6.1.3
    - numpy==1.19.0
    - oauth2client==4.1.3
    - oauthlib==3.1.0
    - opt-einsum==3.2.1
    - packaging==20.4
    - pandas==1.0.4
    - pandocfilters==1.4.2
    - parso==0.7.0
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prometheus-client==0.8.0
    - promise==2.3
    - prompt-toolkit==3.0.5
    - protobuf==3.12.2
    - ptyprocess==0.6.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pygments==2.6.1
    - pylint==2.5.3
    - pyparsing==2.4.7
    - pyrsistent==0.16.0
    - python-dateutil==2.8.1
    - pytz==2020.1
    - pyyaml==5.3.1
    - pyzmq==19.0.2
    - qtconsole==4.7.6
    - qtpy==1.9.0
    - requests==2.24.0
    - requests-oauthlib==1.3.0
    - rsa==3.4.2
    - s3transfer==0.3.3
    - schema==0.7.2
    - scipy==1.4.1
    - send2trash==1.5.0
    - six==1.15.0
    - soupsieve==2.0.1
    - sympy==1.6.1
    - tensorboard==2.2.2
    - tensorboard-plugin-profile==2.2.0
    - tensorboard-plugin-wit==1.7.0
    - tensorflow==2.2.0
    - tensorflow-datasets==3.2.1
    - tensorflow-estimator==2.2.0
    - tensorflow-metadata==0.22.2
    - termcolor==1.1.0
    - terminado==0.8.3
    - testpath==0.4.4
    - toml==0.10.1
    - tornado==6.0.4
    - total-ordering==0.1.0
    - tqdm==4.46.1
    - traitlets==4.3.3
    - typed-ast==1.4.1
    - uritemplate==3.0.1
    - urllib3==1.25.9
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - werkzeug==1.0.1
    - widgetsnbextension==3.5.1
    - wrapt==1.12.1
    - zipp==3.1.0
prefix: /home/ws15dgalvez/miniconda3/envs/100k-hours-lingvo

